algoritmo "Conversor"
var
   angulo, S: Real
inicio
      Escreva("Informe um angulo: ")
      Leia(angulo)
      S <- Sen(GraupRad(angulo))
      Escreva("O seno de ", angulo, " e igual a:", S)
fimalgoritmo

// Funções Aritiméticas
// Abs(Valor absoluto), Exp(Exponenciação), Int(Valor Inteiro),
// RaizQ(Raiz Quadrada), Pi(Retorna Pi), Sen(Seno (rad)),
// Cos(Cosseno(rad)), Tan(Tangente(rad), GraupRad(Graus para Rad).
