algoritmo "Algoritmo004"
// Função : Ler dois números inteiros e mostrar a soma entre eles
// Autor : Lucas Mendes
// Data : 14/11/2023
// Seção de Declarações
   // N1: Primeiro número inteiro
   // N2: Segundo número inteiro
   // S: Soma entre os números inteiros
var
   N1, N2, S: Inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(N1)
      Escreva("Digite outro valor: ")
      Leia(N2)
      S <- N1 + N2
      Escreva("A soma entre", N1, " e", N2, " é igual a", s)
fimalgoritmo
