algoritmo "Algoritmo020"
// Função : Ler um número inteiro e mostrar se ele é par ou ímpar
// Autor : Lucas Mendes
// Data : 21/12/2023
// Seção de Declarações 
   // Num: Valor do número inteiro
var
   Num: Inteiro
inicio
      Escreva("Digite um número inteiro: ")
      Leia(Num)
      Escreval
      Se (Num % 2 = 0) entao
         Escreval("O número:", Num, " é PAR!")
      senao
         Escreval("O número:", Num, " é ÍMPAR!")
      FimSe
fimalgoritmo
