algoritmo "Algoritmo003"
// Função : Ler nome e salário de um funcionário(a) e mostrar uma mensagem
// Autor : Lucas Mendes
// Data : 31/10/2023
// Seção de Declarações 
   // N: Nome do(a) funcionário(a)
   // S: Salário do(a) funcionário(a)
var
   N: Caractere
   S: Real
inicio
      Escreva("Nome do(a) funcionário(a): ")
      Leia(N)
      Escreva("Salário: ")
      Leia(S)
      Escreva("O(A) funcionário(a) ", N, " tem um salário de R$", S, " em Junho.")
fimalgoritmo
