algoritmo "Algoritmo072"
// Função : Criar um programa que preencha automaticamente um vetor númerico
// com 10 posições
// Autor : Lucas Mendes
// Data : 07/02/2024
// Seção de Declarações 
   // v: Vetor
   // i: Contador
   // j: Atribuição de valor
var
   v: vetor[0..9] de Inteiro
   i, j: Inteiro
inicio
      j <- 0
      Para i <- 0 ate 9 faca
           j <- j + 5
           v[i] <- j
           Escreva(j)
      FimPara
fimalgoritmo
