algoritmo "Algoritmo005"
// Função : Ler duas notas em uma matéria e mostrar a média na disciplina
// Autor :  Lucas Mendes
// Data : 15/11/2023
// Seção de Declarações
   // N1: Primeira nota
   // N2: Segunda nota
   // M: Média entre as notas
var
   N1, N2, M: Real
inicio
      Escreva("Nota 1: ")
      Leia(N1)
      Escreva("Nota 2: ")
      Leia(N2)
      M <- (N1 + N2) / 2
      Escreva("A média entre", N1, " e", N2," é igual a", M)
fimalgoritmo
