algoritmo "Algoritmo046"
// Função : Calcular e mostrar na tela o resultado da soma
// Autor : Lucas Mendes
// Data : 09/01/2024
// Seção de Declarações 
   // Cont: Contador
   // S: Soma
var
   Cont, S: Inteiro
inicio
      Cont <- 6
      S <- 0
      Enquanto (Cont <= 100) faca
               Escreva(Cont, " +")
               S <- S + Cont
               Cont <- Cont + 2
      FimEnquanto
      Escreval
      Escreval("A soma entre os números é de: ", S)
fimalgoritmo
