algoritmo "Algoritmo086"
// Função : Criar um programa que tenha um procedimento Gerador() que, quando chamado,
// mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
// Autor : Lucas Mendes
// Data : 25/01/2024
// Seção de Declarações 
var
Procedimento Gerador()
inicio
      Escreval("+-------=======------+")
      Escreval("  Olá, Mundo!         ")
      Escreval("+-------=======------+")
FimProcedimento
inicio
      Gerador()
fimalgoritmo
