algoritmo "Algoritmo067"
// Função : Ler um número inteiro positivo e mostrar na tela uma contagem de 0 até o valor digitado
// Autor : Lucas Mendes
// Data : 16/01/2024
// Seção de Declarações 
   // Cont: Contador
   // N: Número inteiro
var
   Cont, N: Inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(N)
      Escreva("Contagem:")
      Para Cont <- 0 ate N faca
           Escreva(Cont, ",")
      FimPara
      Escreva(" FIM!")
fimalgoritmo
