algoritmo "Algoritmo007"
// Função : Ler um número real e mostrar o seu dobro e a sua terça parte
// Autor : Lucas Mendes
// Data : 15/11/2023
// Seção de Declarações 
   // N: Número real
   // D: Dobro
   // T: Terça parte
var
   N, D, T: Real
inicio
      Escreva("Digite um número: ")
      Leia(N)
      D <- N * 2
      T <- N / 3
      Escreval("O dobro de", N, " é ", D:1:1)
      Escreva("A terça parte de", N, " é ", T:1:5)
fimalgoritmo
